#############################################################################
# Generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#  Jul 19, 2019 11:42:32 AM EDT  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}


proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 2400x1350
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 1
    wm maxsize $top 3844 2108
    wm minsize $top 292 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Nova Scanner"
    vTcl:DefineAlias "$top" "TopLevel" vTcl:Toplevel:WidgetProc "" 1
    canvas $top.can44 \
        -background {#d9d9d9} -borderwidth 4 -closeenough 1.0 -height 673 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 853 
    vTcl:DefineAlias "$top.can44" "Canvas1" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.can44
    button $site_3_0.but45 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Start Scan With Name} 
    vTcl:DefineAlias "$site_3_0.but45" "StartScan" vTcl:WidgetProc "TopLevel" 1
    entry $site_3_0.ent47 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent47" "FileName" vTcl:WidgetProc "TopLevel" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Limit FileName to 8 characters (omit any ending)} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "TopLevel" 1
    listbox $site_3_0.lis49 \
        -background white -borderwidth 2 -disabledforeground {#a3a3a3} \
        -font TkFixedFont -foreground {#000000} -height 312 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -selectbackground {#c4c4c4} -selectforeground black -width 644 
    .top42.can44.lis49 configure -font "TkFixedFont"
    .top42.can44.lis49 insert end text
    vTcl:DefineAlias "$site_3_0.lis49" "Listbox1" vTcl:WidgetProc "TopLevel" 1
    button $site_3_0.but50 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Delete File} 
    vTcl:DefineAlias "$site_3_0.but50" "Delete" vTcl:WidgetProc "TopLevel" 1
    button $site_3_0.but51 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Download File} 
    vTcl:DefineAlias "$site_3_0.but51" "Download" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.but45 \
        -in $site_3_0 -x 750 -y 60 -width 375 -relwidth 0 -height 70 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 40 -y 60 -width 644 -relwidth 0 -height 70 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 30 -y 135 -width 664 -relwidth 0 -height 57 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lis49 \
        -in $site_3_0 -x 40 -y 330 -width 644 -relwidth 0 -height 312 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 750 -y 380 -width 375 -relwidth 0 -height 70 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but51 \
        -in $site_3_0 -x 750 -y 490 -width 375 -height 70 -anchor nw \
        -bordermode ignore 
    canvas $top.can46 \
        -background {#d9d9d9} -borderwidth 4 -closeenough 1.0 -height 663 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 1203 
    vTcl:DefineAlias "$top.can46" "Canvas2" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.can46
    canvas $site_3_0.can53 \
        -background {#d9d9d9} -borderwidth 4 -closeenough 1.0 -height 93 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 1183 
    vTcl:DefineAlias "$site_3_0.can53" "Canvas3" vTcl:WidgetProc "TopLevel" 1
    set site_4_0 $site_3_0.can53
    button $site_4_0.but54 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Connect Via Bluetooth} 
    vTcl:DefineAlias "$site_4_0.but54" "Connect" vTcl:WidgetProc "TopLevel" 1
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text Status: 
    vTcl:DefineAlias "$site_4_0.lab55" "ComStatus" vTcl:WidgetProc "TopLevel" 1
    place $site_4_0.but54 \
        -in $site_4_0 -x 0 -relx 0.02 -y 15 -width 0 -relwidth 0.45 \
        -height 70 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab55 \
        -in $site_4_0 -x 680 -y 20 -width 0 -relwidth 0.4 -height 47 \
        -relheight 0 -anchor nw -bordermode ignore 
    text $site_3_0.tex56 \
        -background white -font TkTextFont -foreground black -height 538 \
        -highlightbackground {#d9d9d9} -highlightcolor {#000000} \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 1154 -wrap word 
    .top42.can46.tex56 configure -font "TkTextFont"
    .top42.can46.tex56 insert end text
    vTcl:DefineAlias "$site_3_0.tex56" "Terminal" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.can53 \
        -in $site_3_0 -x 0 -y 0 -width 1200 -relwidth 0 -height 100 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex56 \
        -in $site_3_0 -x 20 -y 110 -width 1154 -relwidth 0 -height 538 \
        -relheight 0 -anchor nw -bordermode ignore 
    canvas $top.can57 \
        -background {#d9d9d9} -borderwidth 4 -closeenough 1.0 -height 763 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 1183 
    vTcl:DefineAlias "$top.can57" "Canvas4" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.can57
    button $site_3_0.but63 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Move Up} 
    vTcl:DefineAlias "$site_3_0.but63" "JogUp" vTcl:WidgetProc "TopLevel" 1
    button $site_3_0.but67 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Move Down} 
    vTcl:DefineAlias "$site_3_0.but67" "JogDown" vTcl:WidgetProc "TopLevel" 1
    button $site_3_0.but68 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Rotate Left} 
    vTcl:DefineAlias "$site_3_0.but68" "JogLeft" vTcl:WidgetProc "TopLevel" 1
    button $site_3_0.but69 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Rotate Right} 
    vTcl:DefineAlias "$site_3_0.but69" "JogRight" vTcl:WidgetProc "TopLevel" 1
    radiobutton $site_3_0.rad72 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {+ 10 mm/deg} -value False -variable val 
    vTcl:DefineAlias "$site_3_0.rad72" "JogRate" vTcl:WidgetProc "TopLevel" 1
    radiobutton $site_3_0.rad74 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {+ 05 mm/deg} -value False -variable {} 
    vTcl:DefineAlias "$site_3_0.rad74" "JogRate2" vTcl:WidgetProc "TopLevel" 1
    radiobutton $site_3_0.rad75 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {+ 01 mm/deg} -value False -variable {} 
    vTcl:DefineAlias "$site_3_0.rad75" "JogRate3" vTcl:WidgetProc "TopLevel" 1
    button $site_3_0.but76 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Run Home} 
    vTcl:DefineAlias "$site_3_0.but76" "Home" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.but63 \
        -in $site_3_0 -x 400 -y 50 -width 240 -relwidth 0 -height 120 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 400 -y 360 -width 240 -height 120 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but68 \
        -in $site_3_0 -x 260 -y 205 -width 240 -height 120 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 540 -y 205 -width 240 -height 120 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad72 \
        -in $site_3_0 -x 920 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.rad74 \
        -in $site_3_0 -x 920 -y 170 -width 221 -height 57 -anchor nw \
        -bordermode ignore 
    place $site_3_0.rad75 \
        -in $site_3_0 -x 920 -y 230 -width 221 -height 57 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but76 \
        -in $site_3_0 -x 860 -y 560 -width 295 -relwidth 0 -height 150 \
        -relheight 0 -anchor nw -bordermode ignore 
    canvas $top.can58 \
        -background {#d9d9d9} -borderwidth 4 -closeenough 1.0 -height 577 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 1197 
    vTcl:DefineAlias "$top.can58" "Canvas5" vTcl:WidgetProc "TopLevel" 1
    set site_3_0 $top.can58
    label $site_3_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Calibration Info} 
    vTcl:DefineAlias "$site_3_0.lab59" "Label2" vTcl:WidgetProc "TopLevel" 1
    label $site_3_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {Distance Measured:} 
    vTcl:DefineAlias "$site_3_0.lab60" "Dist" vTcl:WidgetProc "TopLevel" 1
    button $site_3_0.but61 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Zero 
    vTcl:DefineAlias "$site_3_0.but61" "ZeroSensor" vTcl:WidgetProc "TopLevel" 1
    label $site_3_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify left \
        -text {SD Card installed: } 
    vTcl:DefineAlias "$site_3_0.lab62" "Label4" vTcl:WidgetProc "TopLevel" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 40 -y 30 -width 376 -relwidth 0 -height 77 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 80 -y 130 -width 776 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 970 -y 120 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 80 -y 230 -width 356 -relwidth 0 -height 47 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can44 \
        -in $top -x 0 -y 0 -width 1200 -relwidth 0 -height 675 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can46 \
        -in $top -x 0 -y 673 -width 0 -relwidth 0.5 -height 0 -relheight 0.5 \
        -anchor nw -bordermode ignore 
    place $top.can57 \
        -in $top -x 1200 -y 0 -width 0 -relwidth 0.5 -height 771 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can58 \
        -in $top -x 1200 -y 771 -width 1200 -relwidth 0 -height 577 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

